# Generated by Django 4.1.7 on 2023-03-12 17:19

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_data_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.FileField(blank=True, upload_to=post.models.upload_path),
        ),
    ]
